"""create_analyzed_docs_table

Revision ID: aa27b5964111
Revises: d92ca2b97576
Create Date: 2025-08-01 11:53:12.571925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa27b5964111'
down_revision: Union[str, Sequence[str], None] = 'd92ca2b97576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyzed_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('issue', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyzed_docs_id'), 'analyzed_docs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyzed_docs_id'), table_name='analyzed_docs')
    op.drop_table('analyzed_docs')
    # ### end Alembic commands ###
